# Generated by Django 4.2.6 on 2024-01-21 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raeume',
            fields=[
                ('raumNR', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('bestuhlung', models.IntegerField()),
                ('ausstattung', models.CharField(choices=[('hoch', 'hoch'), ('mittel', 'mittel'), ('niedrig', 'niedrig')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('vorname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('passwort', models.CharField(max_length=32)),
                ('rolle', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='MyBookings',
            fields=[
                ('buchungsNR', models.AutoField(primary_key=True, serialize=False)),
                ('datum', models.DateField()),
                ('raumNR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.raeume')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.user')),
            ],
        ),
    ]
